#!/usr/bin/env node
// Generates two static, dependency-free HTML pages:
//   public/catalogue/contact-sheet.html   the shipped review page for the live catalogue
//                                         (illustrations + approved real photos) — open it
//                                         directly from disk, or via the running server at
//                                         /catalogue/contact-sheet.html
//   data/catalogue-cache/commons/review.html   a working page for reviewing Commons
//                                         candidates still awaiting a promote/reject
//                                         decision (not shipped; scratch tooling only)
import path from 'node:path';
import fs from 'node:fs';
import { root, dataDir, cacheDir, publicCatalogueDir, loadJson, loadItems } from './lib.mjs';
import { catalogue } from '../../data/catalogue.mjs';

function escapeHtml(value) {
  return String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
}

function page(title, body) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escapeHtml(title)}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; background: #f3efe7; color: #28251d; margin: 0; padding: 24px; }
  h1 { font-size: 1.4rem; margin: 0 0 4px; } h2 { font-size: 1.1rem; margin: 32px 0 12px; border-top: 1px solid #ddd6c4; padding-top: 20px; }
  p.sub { color: #6b6656; margin: 0 0 20px; }
  .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(180px, 1fr)); gap: 16px; }
  figure { margin: 0; background: #fff; border: 1px solid #e4ddc9; border-radius: 10px; overflow: hidden; }
  figure img { width: 100%; aspect-ratio: 1; object-fit: contain; background: #f8f6ef; display: block; }
  figcaption { padding: 8px 10px 10px; font-size: 0.78rem; line-height: 1.4; }
  figcaption .name { font-weight: 600; display: block; }
  figcaption .meta { color: #6b6656; }
  .badge { display: inline-block; font-size: 0.68rem; text-transform: uppercase; letter-spacing: 0.04em; padding: 1px 6px; border-radius: 999px; margin-right: 4px; }
  .badge.top { background: #e4ecf1; color: #2c4a5e; } .badge.bottom { background: #f1e6e0; color: #6e3a24; }
  .badge.illustration { background: #eee; color: #555; } .badge.pending { background: #fff2cc; color: #7a5b00; }
  .count { color: #6b6656; font-weight: 400; }
</style></head><body>${body}</body></html>`;
}

function activeContactSheet() {
  const illustrationCount = catalogue.filter(i => i.image_type === 'illustration').length;
  const realCount = catalogue.length - illustrationCount;
  const cards = catalogue.map(item => `<figure>
    <img src="${escapeHtml(item.image_ref)}" alt="${escapeHtml(item.description)}" loading="lazy">
    <figcaption><span class="badge ${item.category}">${escapeHtml(item.category)}</span>${item.image_type === 'illustration' ? '<span class="badge illustration">illustration</span>' : ''}
      <span class="name">${escapeHtml(item.description)}</span>
      <span class="meta">${escapeHtml(item.id)} · ${escapeHtml(item.colour || '')}${item.pattern && item.pattern !== 'solid' ? ' · ' + escapeHtml(item.pattern) : ''}</span>
    </figcaption></figure>`).join('\n');
  return page('heyTwin catalogue — contact sheet', `
    <h1>heyTwin catalogue <span class="count">(${catalogue.length} active items: ${realCount} photos, ${illustrationCount} illustrations)</span></h1>
    <p class="sub">Everything below is eligible for live recommendations right now. Generated by scripts/catalogue/contact-sheet.mjs — rebuild with <code>npm run catalogue:contact-sheet</code>.</p>
    <div class="grid">${cards}</div>`);
}

function reviewPage() {
  const candidatesPath = path.join(cacheDir, 'commons', 'candidates.json');
  const candidates = loadJson(candidatesPath, []);
  const pending = candidates.filter(c => c.status === 'pending_review' && c.review_thumb);
  const rejected = candidates.filter(c => c.status === 'rejected');
  const items = loadItems();
  const alreadyImported = new Set(items.map(i => i.source_page));
  const stillPending = pending.filter(c => !alreadyImported.has(c.sourcePage));
  const cards = stillPending.map(c => `<figure>
    <img src="review/${escapeHtml(path.basename(c.review_thumb))}" alt="${escapeHtml(c.title)}" loading="lazy">
    <figcaption><span class="badge ${c.target_category}">${escapeHtml(c.target_category)}</span><span class="badge pending">${escapeHtml(c.license || 'unknown licence')}</span>
      <span class="name">${escapeHtml(c.title.replace(/^File:/, ''))}</span>
      <span class="meta">hint: ${escapeHtml(c.subcategory_hint || '—')} · from ${escapeHtml(c.category_source)}<br>${escapeHtml(c.author || 'author not extracted')}</span>
      <span class="meta"><a href="${escapeHtml(c.sourcePage)}">source page</a></span>
    </figcaption></figure>`).join('\n');
  return page('Commons candidates awaiting review', `
    <h1>Commons candidates awaiting review <span class="count">(${stillPending.length} pending, ${rejected.length} auto-rejected, ${items.length} already promoted)</span></h1>
    <p class="sub">Scratch tooling, not shipped. To promote one: copy its fields into data/sources.json -> wikimedia_commons_files with reviewed:true, a name, colour_primary, pattern, subcategory and image_type, then run <code>npm run catalogue:import</code>.</p>
    <div class="grid">${cards}</div>`);
}

fs.mkdirSync(publicCatalogueDir, { recursive: true });
fs.writeFileSync(path.join(publicCatalogueDir, 'contact-sheet.html'), activeContactSheet());
console.log(`Wrote ${path.join(publicCatalogueDir, 'contact-sheet.html')}`);

const reviewOut = path.join(cacheDir, 'commons', 'review.html');
fs.writeFileSync(reviewOut, reviewPage());
console.log(`Wrote ${reviewOut}`);
