import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { createSearchProfile, metadataSearchAttributes } from '../lib/search-profile.mjs';
import { createProductSearch } from '../lib/product-search.mjs';
const attributes = { category: 'top', garment_type: 'shirt', colour: 'cream', details: 'cream knitwear', material: 'unspecified' };
const asset = { data: Buffer.from('test-generated-image-only'), contentType: 'image/png' };
const raw = (values = {}) => ({ usable: true, attributes: Object.fromEntries(Object.entries({ garment_type: 'knit top', sleeves: 'long sleeve', neckline: 'crew neck', closure: 'pullover', colour: 'cream', ...values }).map(([key, value]) => [key, { value, confidence: .95 }])) });
async function directory(t) { const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'search-profile-')); t.after(() => fs.rm(dir, { recursive: true, force: true })); return dir; }

test('corrects imported knitwear metadata without mutating generation attributes', () => {
  assert.equal(metadataSearchAttributes(attributes).garment_type, 'knit top');
  assert.equal(attributes.garment_type, 'shirt');
});
test('inspects generated bytes, deduplicates calls and persists only accepted attributes', async t => {
  const storageDir = await directory(t); let calls = 0;
  const profile = createSearchProfile({ storageDir, model: 'test', provider: async (prompt, image) => {
    calls++; assert.match(prompt, /sleeves/); assert.equal(image, `data:image/png;base64,${asset.data.toString('base64')}`);
    await new Promise(resolve => setTimeout(resolve, 5));
    return { ...raw(), untrusted_extra: 'not persisted' };
  } });
  const [first, second] = await Promise.all([profile.resolve({ attributes, asset }), profile.resolve({ attributes, asset })]);
  assert.equal(calls, 1); assert.equal(first.basis, 'generated_image'); assert.equal(first.attributes.sleeves, 'long sleeve'); assert.deepEqual(second.attributes, first.attributes);
  const cached = createSearchProfile({ storageDir, model: 'test', provider: async () => { throw new Error('cache should avoid provider'); } });
  assert.equal((await cached.resolve({ attributes, asset })).cached, true);
  const record = await fs.readFile(path.join(storageDir, (await fs.readdir(storageDir))[0]), 'utf8');
  assert.doesNotMatch(record, /not persisted|data:image|test-generated-image-only/);
});
test('image or model changes invalidate the profile while low-confidence details stay unclaimed', async t => {
  const storageDir = await directory(t); let calls = 0;
  const provider = async () => { calls++; const result = raw(); result.attributes.material = { value: 'cashmere', confidence: .4 }; return result; };
  const profile = createSearchProfile({ storageDir, model: 'one', provider });
  const first = await profile.resolve({ attributes, asset });
  assert.equal(first.attributes.material, 'unspecified'); assert.ok(!first.checked_fields.includes('material'));
  await profile.resolve({ attributes, asset: { ...asset, data: Buffer.from('different image') } });
  await createSearchProfile({ storageDir, model: 'two', provider }).resolve({ attributes, asset });
  assert.equal(calls, 3);
});
test('unavailable or invalid visual analysis falls back honestly and suppresses immediate retries', async t => {
  const storageDir = await directory(t); let calls = 0, now = 0;
  const profile = createSearchProfile({ storageDir, now: () => now, provider: async () => { calls++; return { usable: false }; } });
  const first = await profile.resolve({ attributes, asset });
  assert.equal(first.basis, 'description'); assert.match(first.note, /could not be checked/);
  await profile.resolve({ attributes, asset }); assert.equal(calls, 1);
  now = 60001; await profile.resolve({ attributes, asset }); assert.equal(calls, 2);
  assert.equal((await profile.resolve({ attributes })).basis, 'description'); assert.equal(calls, 2);
});
test('cross-category images and invalid binary assets cannot override the paired garment', async t => {
  const profile = createSearchProfile({ storageDir: await directory(t), provider: async () => raw({ garment_type: 'jeans' }) });
  const mismatch = await profile.resolve({ attributes, asset });
  assert.equal(mismatch.basis, 'description'); assert.equal(mismatch.attributes.garment_type, 'knit top');
  const invalid = await profile.resolve({ attributes, asset: { ...asset, contentType: 'text/html' } });
  assert.equal(invalid.basis, 'description');
});

test('observed long sleeves override stale description and reach the Shopping query and filter', async t => {
  const profile = createSearchProfile({ storageDir: await directory(t), provider: async () => raw({ garment_type: 'shirt', colour: 'white', sleeves: 'long sleeve', neckline: 'collared', closure: 'button front' }) });
  const observed = await profile.resolve({ asset, attributes: { category: 'top', garment_type: 'shirt', colour: 'white', details: 'short sleeves, crew neckline' } });
  const queries = [];
  const search = createProductSearch({ env: { SERPAPI_API_KEY: 'fixture-key' }, fetchImpl: async url => {
    queries.push(new URL(url).searchParams.get('q'));
    return new Response(JSON.stringify({ shopping_results: [
      { title: 'White long sleeve button down shirt', link: 'https://shop.example/long', source: 'Fixture Shop' },
      { title: 'White short sleeve shirt', link: 'https://shop.example/short', source: 'Fixture Shop' },
      { title: 'White relaxed T-shirt', link: 'https://shop.example/tee', source: 'Fixture Shop' },
    ] }));
  } });
  const result = await search.search({ attributes: observed.attributes });
  assert.equal(queries[0], 'white long sleeve collared button front shirt');
  assert.deepEqual(result.products.map(item => item.url), ['https://shop.example/long']);
});
